using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;

namespace KMPBookingCore.Database
{
    public abstract class DbObject : INotifyPropertyChanged
    {
        public enum DbState
        {
            Synced,
            New,
            Dirty,
        }

        public DbState ObjDbState { get; protected set; }

        protected DbObject()
        {
            ObjDbState = LoadingFromDb ? DbState.Synced : DbState.New;
        }

        public event PropertyChangedEventHandler PropertyChanged;

        public static bool LoadingFromDb { get; private set; } = false;
        private static readonly Stack<bool> _loadingFromDbStack = new Stack<bool>();

        public static void PushLoadingFromDb(bool value)
        {
            _loadingFromDbStack.Push(LoadingFromDb);
            LoadingFromDb = value;
        }

        public static void PopLoadingFromDb()
        {
            LoadingFromDb = _loadingFromDbStack.Pop();
        }

        protected void RaiseEventChanged(string name)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
            if (!LoadingFromDb)
            {
                if (ObjDbState == DbState.Synced)
                {
                    ObjDbState = DbState.Dirty;
                }
            }
        }

        public virtual IEnumerable<(string, string)> GetFieldValuePairs()
        {
            var properties = GetType().GetProperties();
            foreach (var property in properties) 
            {
                var dbfield = property.GetCustomAttribute<DbFieldAttribute>();
                bool include = (dbfield != null);
                if (!include)
                {
                    var primaryKey = property.GetCustomAttribute<DbPrimaryKeyAttribute>();
                    include = (primaryKey != null && !primaryKey.IsAutoGenerated);
                }
                if (include)
                {
                    var fieldName = DbUtils.GetDbFieldName(property);
                    var fieldValue = FieldToDbString(property.PropertyType, property.GetValue(this), property);
                    yield return (fieldName, fieldValue);
                }
            }
        }

        protected virtual string FieldToDbString(Type type, object value, PropertyInfo property)
        {
            return DbUtils.ToDbString(type, value, property);
        }
    }
}
