using System;

namespace KMPBookingCore.Database
{
    public class DbPrimaryKeyAttribute : Attribute
    {
        public DbPrimaryKeyAttribute() { }
        public DbPrimaryKeyAttribute(bool autoGenerated)
        {
            IsAutoGenerated = autoGenerated;
        }
        public bool IsAutoGenerated { get; set; } = true;
    }
}
